name: dart_app
description: A new Dart project.

publish_to: 'none'

version: 1.0.0+1

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  fpdart: ^0.6.0 # Check out the latest version

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.3
